dtb-$(CONFIG_ARCH_FSL_IMX8MM) += $(DTB_FILE_NAME)-0.dtb \
				 $(DTB_FILE_NAME)-1.dtb \
				 $(DTB_FILE_NAME)-2.dtb \
				 $(DTB_FILE_NAME)-3.dtb \
				 $(DTB_FILE_NAME)-4.dtb \
				 $(DTB_FILE_NAME)-5.dtb

always          := $(dtb-y)
subdir-y        := $(dts-dirs)
clean-files     := *.dtb
